/*
 * This source file was generated by the Gradle 'init' task
 */
package javaprojects;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloWorldTest {

    @Test 
    void appHasAGreeting() {

        HelloWorld helloWorld = new HelloWorld();
        assertNotNull(helloWorld.getGreeting());
    }
}
