/*
 * This source file was generated by the Gradle 'init' task
 */
package javaprojects;

public class App {

    public static void main(String[] args) {

        HelloWorld helloWorld = new HelloWorld();

        System.out.println(helloWorld.getGreeting());
    }
}
